---
name: jp-laptop
full_name: jp-laptop script
type: app
owner_type: project
parent: 18F/laptop
stage: live
description: >
  Shell script for installing core utils.
tags:
- initialization
testable: false
team:
- github: jonthebastard
  id: Jonathan Pirro
  role: developer
stack:
- Bash
- Zsh
- Homebrew
impact: >
  Allows for quick and easy setup of basic utils on macOS.
licenses:
  thoughtbot-laptop:
    name: MIT
    url: https://github.com/thoughtbot/laptop/blob/master/LICENSE
  18F-laptop:
    name: CC0
    url: https://github.com/18F/laptop/blob/master/LICENSE.md