#!/bin/sh

# files to pull from repo
read -r -d '' files <<'EOF'
.zshrc
Brewfile
mac
EOF

cd ~
for file in $(echo $files | sed -e 's/\n/ /') ; do
  curl -fsSL https://raw.githubusercontent.com/jonthebastard/laptop/master/files/$file > $file
done

/usr/bin/env bash mac 2>&1 | tee laptop.log

. ~/.zshrc
